apiVersion: v1
kind: Service
metadata:
  name: rent-service
  labels:
    app: rent
spec:
  selector:
    app: rent
  ports:
    - name: rent-service
      port: 50052
      targetPort: 50052
    - name: metrics
      port: 9091
      targetPort: 9091
  type: ClusterIP
